name: aws-kms-encrypter
trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

variables:
  GO111MODULE: 'on'      

stages:
  - stage: test
    dependsOn: []
    jobs:
      - job: unit_tests
        displayName: Run Unit Tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - script: go mod download && go test -v ./...
            displayName: 'Run go test command'
