version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.12.5
        environment:
            GO111MODULE: 'on'
        working_directory: /go/src/github.com/darkraiden/aws-kms-encrypter
        steps:
            - checkout
            - run:
                  name: fetch dependencies
                  command: |
                      go mod vendor
            - run:
                  name: run tests
                  command: |
                      go test ./...
            - run:
                  name: run build
                  command: |
                      go build -v
